name: Deploy SQL to Snowflake

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      ref: Demo

    - name: cwd
      run: |
        pwd
        ls

    - name: Replace placeholders in SQL template
      run: |
        # Replace placeholders with environment-specific values
        sed -i "s/%DevDBName%}}/${{ secrets.DEVDBNAME }}/g" dbscripts/DBNew.sql

    - name: Upload artifact file
      uses: actions/upload-artifact@v2
      with:
        name: modified_file
        path: dbscripts/DBNew.sql
    # - name: Deploy SQL to Snowflake
    #   run: |
    #     # Use Snowflake CLI or any other tool to deploy SQL files
    #     snowsql -f template.sql -o friendly_format
