name: Deploy SQL to Snowflake

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: Demo

    - name: cwd
      run: |
        pwd
        ls

    - name: Replace placeholders in SQL template
      run: |
        # Replace placeholders with environment-specific values
        sed -i "s/%DemoDBNAME%/${{ secrets.DEMODBNAME }}/g" dbscripts/AlterScript.sql

    - name: Upload artifact file
      uses: actions/upload-artifact@v2
      with:
        name: modified_file
        path: dbscripts/AlterScript.sql

    - name: Install Snowflake CLI
      run: |
        pip install snowflake-connector-python
        
    - name: Deploy SQL to Snowflake
      run: |
        # Use Snowflake CLI or any other tool to deploy SQL files
       
        snowsql -a "$SF_ACCOUNT" -u "$SF_USERNAME" -p "$SF_PASSWORD" -f dbscripts/AlterScript.sql -o friendly_format
