name: Deploy SQL to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: cwd
      run: |
        pwd
        ls

    # - name: Replace placeholders in SQL template
    #   run: |
    #     # Determine environment-specific values
    #     if [ "${{ github.event_name }}" == "pull_request" ]; then
    #       ENVIRONMENT="dev"
    #     else
    #       ENVIRONMENT="uat"
    #     fi
        
    #     # Replace placeholders with environment-specific values
    #     sed -i "s/{{DB_NAME}}/${{ secrets.DB_NAME_${{ ENVIRONMENT }}}}/g" template.sql

    # - name: Deploy SQL to Snowflake
    #   run: |
    #     # Use Snowflake CLI or any other tool to deploy SQL files
    #     snowsql -f template.sql -o friendly_format
