name: Deploy SQL to Snowflake

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA 
    env:
      SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
      SNOWSQL_DATABASE: ${{ secrets.SF_DATABASE }}
      SNOWSQL_SCHEMA: ${{ secrets.SF_SCHEMA }}
      SNOWSQL_ROLE: ${{ secrets.SF_ROLE }}
      SNOWSQL_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: Demo

    - name: cwd
      run: |
        pwd
        ls

    - name: Replace placeholders in SQL template
      run: |
        # Replace placeholders with environment-specific values
        sed -i "s/%DemoDBNAME%/${{ secrets.DEMODBNAME }}/g" dbscripts/AlterScript.sql

    - name: Upload artifact file
      uses: actions/upload-artifact@v2
      with:
        name: modified_file
        path: dbscripts/AlterScript.sql

    - name: Install SnowSQL
      run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
          
    - name: Version
      run: |
          ~/bin/snowsql --bootstrap-version
          
    - name: Upload artifact to SnowSQL
      run: |
          ~/bin/snowsql -q 'put file://'$(pwd)'/dbscripts/AlterScript.sql @~/Demo overwrite=true' -o friendly=false
          
    - name: Deploy SQL to Snowflake
      run: |     
        ~/bin/snowsql -a "$SF_ACCOUNT" -u "$SF_USERNAME" -p "$SF_PASSWORD" -f dbscripts/AlterScript.sql
        
    # - name: Deploy SQL to Snowflake
    #   run: |
    #       ~/bin/snowsql -q 'CREATE OR REPLACE PROCEDURE  MYPROC(message STRING)
    #                                     RETURNS STRING
    #                                     LANGUAGE PYTHON
    #                                     RUNTIME_VERSION = '\''3.8'\''
    #                                     PACKAGES = ('')
    #                                     IMPORTS = ('\''@~/${{ github.ref_name }}/storedproc.py'\'')
    #                                     HANDLER = '\''storedproc.run'\'';' -o friendly=false
